// ------------------------------------------------------------------------------
// -----  EVENT  ----------------------------------------------------------------
// ---------- https://discord.js.org/#/docs/main/stable/class/Client ------------
//   ※　わざわざ変数の型が書かれているけど、ぶっちゃけ、特に意味ないです。
//       必要なのは、変数の個数。
// ------------------------------------------------------------------------------

export const EventList = 
{
	"applicationCommandCreate": [ "ApplicationCommand" ],
	"applicationCommandDelete": [ "ApplicationCommand" ],
	"applicationCommandUpdate": [ "ApplicationCommand", "ApplicationCommand" ],
	"channelCreate": [ "GuildChannel" ],
	"channelDelete": [ "any" ],
	"channelPinsUpdate": [ "TextBasedChannels", "Date" ],
	"channelUpdate": [ "any", "any" ],
	"debug": [ "string" ],
	"emojiCreate": [ "GuildEmoji" ],
	"emojiDelete": [ "GuildEmoji" ],
	"emojiUpdate": [ "GuildEmoji","GuildEmoji" ],
	"error": [ "any" ],
	"guildBanAdd": [ "GuildBan" ],
	"guildBanRemove": [ "GuildBan" ],
	"guildCreate": [ "Guild" ],
	"guildDelete": [ "Guild" ],
	"guildIntegrationsUpdate": [ "Guild" ],
	"guildMemberAdd": [ "GuildMember" ],
	"guildMemberAvailable": [ "GuildMember" ],
	"guildMemberRemove": [ "GuildMember" ],
	"guildMembersChunk": [ "any" , "Guild", "GuildMembersChunk" ],
	"guildMemberUpdate": [ "any", "any" ],
	"guildUnavailable": [ "Guild" ],
	"guildUpdate": [ "Guild", "Guild" ],
	"interactionCreate": ["any"],
	"invalidRequestWarning": [ "InvalidRequestWarningData" ],
	"inviteCreate": [ "Invite" ],
	"inviteDelete": [ "Invite" ],
	"messageCreate": [ "Message" ],
	"messageDelete": [ "Message" ],
	"messageDeleteBulk": [ "any" ],
	"messageReactionAdd": [ "MessageReaction", "User" ],
	"messageReactionRemove": [ "MessageReaction", "User" ],
	"messageReactionRemoveAll": [ "Message" ],
	"messageReactionRemoveEmoji": [ "MessageReaction" ],
	"messageUpdate": [ "Message","Message" ],
	"presenceUpdate": [ "Presence", "Presence" ],
	"rateLimit": [ "RateLimitData" ],
	"ready": ["Client"],
	"roleCreate": [ "Role" ],
	"roleDelete": [ "Role" ],
	"roleUpdate": [ "Role","Role" ],
	"shardDisconnect": [ "any", "any" ],
	"shardError": [ "any", "any" ],
	"shardReady": [ "any", "any" ],
	"shardReconnecting": [ "any" ],
	"shardResume": [ "any", "any" ],
	"stageInstanceCreate": [ "StageInstance" ],
	"stageInstanceDelete": [ "StageInstance" ],
	"stageInstanceUpdate": [ "StageInstance", "StageInstance" ],
	"stickerCreate": [ "Sticker" ],
	"stickerDelete": [ "Sticker" ],
	"stickerUpdate": [ "Sticker", "Sticker" ],
	"threadCreate": [ "ThreadChannel" ],
	"threadDelete": [ "ThreadChannel" ],
	"threadListSync": [ "any" ],
	"threadMembersUpdate": [ "any", "any" ],
	"threadMemberUpdate": [ "ThreadMember", "ThreadMember" ],
	"threadUpdate": [ "ThreadChannel", "ThreadChannel" ],
	"typingStart": [ "Typing" ],
	"userUpdate": [ "User", "User" ],
	"voiceStateUpdate": [ "VoiceState", "VoiceState" ],
	"warn": [ "any" ],
	"webhookUpdate": [ "TextChannel" ],
}